---
AllCops:
  Exclude:
  - vendor/**/*
Documentation:
  Enabled: false
ParameterAlignment:
  Enabled: true
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
EmptyLinesAroundBlockBody:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
MethodLength:
  Max: 40
NumericLiterals:
  MinDigits: 10
Metrics/BlockLength:
  Max: 35
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 10
Metrics/AbcSize:
  Max: 30
# Lint/AmbiguousBlockAssociation is incompatible with RSpec
# https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Enabled: false
